#Build Steps

steps:

# Prints info
- name: 'gcr.io/cloud-builders/gcloud'
  id: gcloud
  args: ['info']

- name: 'gcr.io/cloud-builders/gcloud'
  id: gcloud_vm
  args: ['compute instances create example-instance-1 --zone us-central1-a' ]
  
# Copy sample file
- name: 'gcr.io/cloud-builders/gsutil'
  id: copy
  args: ['cp', 'create_vm.sh', 'gs://${_BUCKET_NAME}/create_vm.sh']

substitutions:
    _BUCKET_NAME: tfstate-backup # default value
