#Build Steps

steps:

# Prints gcloud info
- name: 'gcr.io/cloud-builders/gcloud'
  id: gcloud
  args: ['info']

# creates ins using CLI
- name: 'gcr.io/cloud-builders/gcloud'
  id: gcloud_vm
  args: ['compute', 'instances', 'create', '${_INS_NAME}', '--zone', 'us-central1-a']

# creates ins using Shell
- name: 'gcr.io/cloud-builders/gcloud'
  id: gcloud_vm2
  entrypoint: 'bash'
  args: ['-c', 'chmod +x create_vm.sh && ./create_vm.sh']
  
# Copy sample file to the bucket
- name: 'gcr.io/cloud-builders/gsutil'
  id: copy
  args: ['cp', 'create_vm.sh', 'gs://${_BUCKET_NAME}/create_vm.sh']

# Clone a public repo
- name: 'gcr.io/$PROJECT_ID/git'
  id: git
  args: ['clone', 'https://github.com/sriman-biarca/dep-manager-code.git']
  #dir: 'dep-manager-code'

# Runs a deployment manager script which is in cloned repo
- name: 'gcr.io/cloud-builders/gcloud'
  #entrypoint: 'bash'
  #args: ['-c', 'cd dep-manager-code && ls']
  args: ['deployment-manager', 'deployments', 'create', 'test', '--config', 'dep-manager-code/service-account/service_account.yaml']
  waitFor: ['git']
  
# Vars defined here
substitutions:
    _BUCKET_NAME: tfstate-backup
    _INS_NAME: example-instance-1
