#Build Steps

steps:
# Clone a public repo.
- name: 'gcr.io/$PROJECT_ID/git'
  args: ['clone', 'https://github.com/sriman-biarca/dep-manager-code.git']
  dir: 'dep-manager-code'



- name: 'gcr.io/cloud-builders/gcloud'
  args: ['deployment-manager', 'deployments', 'create', 'test', '--config', 'dep-manager-code/service-account/service_account.yaml']
